- name: mysql configuration
  hosts: mysql
  become: yes
  tasks:
  - name: ansible to install boto3 & botocore
    ansible.builtin.pip:
      name: 
      - boto3
      - botocore
      executable: pip3.9

#Inatalling mysql server      
  - name: install mysql server
    ansible.builtin.package:
      name: mysql-server
      state: present

#start the mysql-server 
  - name: start mysql server
    ansible.builtin.service:
      name: mysqld
      state: started
      enabled: yes
 